### ISSUE TITLE
Dispatch/complete bugs

### ISSUE THREAD

**Issue by ciuchs** [codesidian/Python-MissionChiefBot#28]
Oh no, an error occurred.
list.remove(x): x not in list
Please create an issue on github or post in our discord
Include your output and the debug.log file so we can debug it! :)

also vehicles are not being dispatched, not sure if i have my helper file is correct.

[Python-MissionChiefBot-master.zip](https://github.com/codesidian/Python-MissionChiefBot/files/4216205/Python-MissionChiefBot-master.zip)

**Comment by jackbayliss** [comment]
@ciuchs  Thanks for the report, this happens when missions come up as completed for some reason.  I'm aware of the issue and will debug when I have chance. Your vehicles should despatch file as long as your vehicle type is in the requirements- you should see in the json folder your vehicles.json file- that'll tell you the types you need.  Eventually I'll make it so you won't need to edit the helpers.py and it'll get generated from your vehicles.

**Comment by ciuchs** [comment]
I was trying to populate the helper file based on the mission.json file and the vehicle.json file but I may have messed it up somewhere in doing so since nothing dispatches. I will look at again later. That would be awesome to not have to edit the helper file. Looking forward to seeing that implement in the future. Thanks

**Comment by jackbayliss** [comment]
I'll get around to it eventually! Should be super easy as we have everything we need in the vehicles.json- I'll fix the issue above too.

**Comment by jackbayliss** [comment]
This is fixed by https://github.com/codesidian/Python-MissionChiefBot/commit/5ed915d43871febb917b352f549b21698fbd6461#diff-099ae1266215a0cad70f05a7bc2a6035R93 

In terms of making a self making list, it's unfortunately not that easy. We can tell that for example a Water Pump is a water pump, but there's no way to say - Hey that's a fire engine.  It is something i'm still looking into.
